.\"/*
.\" * All rights reserved
.\" *Copyright (c) [Year] [name of copyright holder]
.\" *[Software Name] is licensed under Mulan PSL v2.
.\" *You can use this software according to the terms and conditions of the Mulan PSL v2.
.\" *You may obtain a copy of Mulan PSL v2 at:
.\" *         http://license.coscl.org.cn/MulanPSL2
.\" *THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
.\" *EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
.\" *MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
.\" */
.\".
.TH "keentune-brain" "8" "5 May 2022" "OpenAnolis KeenTune SIG" "KeenTune"
.SH NAME
KeenTune-brain - AI tuning Engine of 'KeenTune' system parameter optimization system
.SH SYNOPSIS
\fBKeenTune-brain\fP
.SH DESCRIPTION
\fBKeenTune-brain\fR KeenTune-brain is an AI tuning Engine of 'KeenTune' system parameter optimization system. KeenTune-brain implements a variety of intelligent tuning algorithms. It generates a candidate configuration for KeenTune system, obtains an evaluation from Keentune-bench, and gives the optimal parameter configuration.

.SH "Run"
.
.TP
\fBsystemctl start keentune-brain.service\fR

.SH "BUGS"
Report bugs at: https://gitee.com/anolis/keentuned/issues
                                                                                                                                                                                                1,1          顶端
